version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - '8080:3000'
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:14.0
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
