# Используйте образ Node.js для разработки
FROM node:18.1.0 AS development

ENV NODE_ENV=development

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml .dockerignore ./

# Установите глобально pnpm и некоторые дополнительные зависимости
RUN npm install -g pnpm
RUN pnpm install glob rimraf

# Установите зависимости приложения
RUN pnpm install --frozen-lockfile

# Скопируйте остальные файлы приложения
COPY . .

COPY prisma ./prisma

RUN npx prisma generate

# Укажите команду для запуска приложения в режиме разработки
CMD ["pnpm", "start:dev"]

